// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/ra1n6ow/webook/internal/repository"
	"github.com/ra1n6ow/webook/internal/repository/cache"
	"github.com/ra1n6ow/webook/internal/repository/dao"
	"github.com/ra1n6ow/webook/internal/service"
	"github.com/ra1n6ow/webook/internal/web"
	"github.com/ra1n6ow/webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	handlerFunc := ioc.InitSessionMiddleware()
	v := ioc.InitMiddlewares(handlerFunc)
	db := ioc.InitDB()
	userDAOer := dao.NewUserDAO(db)
	cmdable := ioc.InitRedis()
	userCacher := cache.NewUserCache(cmdable)
	userRepositoryer := repository.NewUserRepository(userDAOer, userCacher)
	userServicer := service.NewUserService(userRepositoryer)
	codeCacher := cache.NewCodeCache(cmdable)
	codeRepositoryer := repository.NewCodeRepository(codeCacher)
	servicer := ioc.InitSms()
	codeServicer := service.NewCodeService(codeRepositoryer, servicer)
	userHandler := web.NewUserHandler(userServicer, codeServicer)
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}
